logger: 
    name: TestRest
    fileloglevel: DEBUG
    consoleloglevel: DEBUG
    file: /tmp/what2.txt
test:
    global:
        baseurl: <optional>
    testCase1:
        authenticator:  
            class: testrest.authenticator.BasicAuthenticator.BasicAuthenticator
            params:
                username: wsuser
                password: wspassword
        url: http://localhost:9000/contact/4
        method: GET
        params: {}
        header:
            Content-Type: application/json
        assertions:
            testCase1_asserter1:
                class: testrest.asserter.AssertTrue.AssertTrue 
                expr: expression
                msg: Error 1
    testCase2:
        authenticator:  
            class: testrest.authenticator.BasicAuthenticator.BasicAuthenticator
            params:
                username: wsuser
                password: wspassword
        url: http://localhost:9000/contact
        method: POST
        params: 
            firstName: TESTREST
            lastName: BAR
            phone: 0912345678
        header:
            Content-Type: application/json
        assertions:
            testCase2_asserter1:
                class: testrest.asserter.AssertIsNotNone.AssertIsNotNone
                expr: 
                    - header
                    - Location
                msg: No location header set - creation might have failed.
    testCase3:
        authenticator:  
            class: testrest.authenticator.BasicAuthenticator.BasicAuthenticator
            params:
                username: wsuser
                password: wspassword
        url: testCase2Alias
        method: DELETE
        params: {}
        assertions:
            testCase3_asserter1:
                class: testrest.asserter.AssertTrue.AssertTrue
                expr: expression
                msg:  Error 6
        regress:
            testCase2:
                alias: testCase2Alias
                path: 
                    - header
                    - Location

                
           
