logger: 
    name: TestRest
    fileloglevel: DEBUG
    consoleloglevel: INFO
    file: /tmp/what2.txt
test:
    global:
        baseurl: <optional>
    testCase1:
        authenticator: authenticator
        url: whatever
        method: POST
        params: 
            param1: lslsls
            param2: whatever
        assertions:
            testrest.asserter.AssertTrue.AssertTrue: 
                expr: expression
                msg: Error 1
    testCase2:
        authenticator: authenticator2
        url: whatever2
        method: GET
        params: 
            param1: waatever
            param2: whatever
            param3: somewhat
        assertions:
            testrest.asserter.AssertTrue.AssertTrue: 
                expr: expression
                msg: Error 2 
            i.do.not.exist: 
                expr: expression
                msg: Error 3
            testrest.asserter.AssertTrue.IDoNotExist: 
                expr: expression
                msg: Error 4
            testrest.asserter.AssertTrue.IDoNotExist: 
                expr: expression
                msg: Error 5
    testCase3:
        authenticator: authenticator2
        url: whatever2
        method: DELETE
        params: 
            param1: waatever
            param2: whatever
            param3: somewhat
        assertions:
            testrest.asserter.AssertTrue.AssertTrue: 
                expr: expression
                msg:  Error 6
            testrest.asserter.AssertTrue.AssertTrue: 
                expr: expression
                msg:  Error 7 
           
