logger: 
    name: TestRest
    fileloglevel: DEBUG
    consoleloglevel: INFO
    file: /tmp/what2.txt
test:
    global:
        baseurl: <optional>
    testCase1:
        authenticator: authenticator
        url: whatever
        method: (GET|POST|DELETE|WHATEVER)
        params: 
            param1: lslsls
            param2: whatever
        assertions:
            testrest.asserter.AssertTrue.AssertTrue: whatever
            assertEquals: whatever
    testCase2:
        authenticator: authenticator2
        url: whatever2
        method: (GET|POST|DELETE|WHATEVER)
        params: 
            param1: waatever
            param2: whatever
            param3: somewhat
        assertions:
            testrest.asserter.AssertTrue.AssertTrue: whatever
            assertEquals: whatever
    testCase3:
        authenticator: authenticator2
        url: whatever2
        method: (GET|POST|DELETE|WHATEVER)
        params: 
            param1: waatever
            param2: whatever
            param3: somewhat
        assertions:
            testrest.asserter.AssertTrue.AssertTrue: whatever
            assertEquals: whatever
            
