logger: 
    name: TestRest
    fileloglevel: DEBUG
    consoleloglevel: INFO
    file: /tmp/what2.txt
test:
    global:
        baseurl: <optional>
    testCase1:
        authenticator:  
            class: testrest.authenticator.BasicAuthenticator.BasicAuthenticator
            params:
                username: myBasicAuthUsername
                password: myBasicAuthPassword
        url: whatever
        method: POST
        params: 
            param1: lslsls
            param2: whatever
        assertions:
            testCase1_asserter1:
                class: testrest.asserter.AssertTrue.AssertTrue 
                expr: expression
                msg: Error 1
    testCase2:
        authenticator:  
            class: testrest.authenticator.BasicAuthenticator.BasicAuthenticator
            params:
                username: myBasicAuthUsername
                password: myBasicAuthPassword
        url: whatever2
        method: GET
        params: 
            param1: waatever
            param2: whatever
            param3: somewhat
        assertions:
            testCase2_asserter1:
                class: testrest.asserter.AssertTrue.AssertTrue 
                expr: expression
                msg: Error 2
            testCase2_asserter2: 
                class: i.do.not.exist 
                expr: expression
                msg: Error 3
            testCase2_asserter3:
                class: testrest.asserter.AssertTrue.IDoNotExist
                expr: expression
                msg: Error 4
            testCase2_asserter4:
                class: testrest.asserter.AssertTrue.IDoNotExist
                expr: expression
                msg: Error 5
    testCase3:
        authenticator:  
            class: testrest.authenticator.BasicAuthenticator.BasicAuthenticator
            params:
                username: myBasicAuthUsername
                password: myBasicAuthPassword
        url: whatever2
        method: DELETE
        params: 
            param1: waatever
            param2: whatever
            param3: somewhat
        assertions:
            testCase3_asserter1:
                class: testrest.asserter.AssertTrue.AssertTrue
                expr: expression
                msg:  Error 6
            testCase3_asserter2:
                class: testrest.asserter.AssertTrue.AssertTrue
                expr: expression
                msg:  Error 7 
           
